version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 727796463450.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t react-egan-air-ui .
      - docker tag react-egan-air-ui:latest 727796463450.dkr.ecr.us-east-1.amazonaws.com/react-egan-air:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 727796463450.dkr.ecr.us-east-1.amazonaws.com/react-egan-air:latest

artifacts:
  files:
    - "**/*"
